export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const DATA_FILTER_BY_NAME = 'DATA_FILTER_BY_NAME';
export const DATA_FILTER_BY_SCORE = 'DATA_FILTER_BY_SCORE';
export const DATA_FILTER_BY_ORDER_BY = 'DATA_FILTER_BY_ORDER_BY';
export const DATA_FILTER_RESET = 'DATA_FILTER_RESET';
